- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker is present
  apt:
    name: docker.io
    state: latest
    force: yes
  tags: [docker]

- name: User "ubuntu" has group docker
  user: name=ubuntu groups=docker append=yes

- name: Group is applied in current session
  shell: newgrp

- name: Python-pip is present
  apt: name=python-pip state=present
  tags: [docker]



- name: Docker-py is present
  pip: name=docker-py version=0.4.0 state=present
  sudo: yes
  tags: [docker]


- name: Docker has settings folder
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0777 owner=ubuntu group=docker

- name: Proxy config for Docker
  template: src=http_proxy.conf dest=/etc/systemd/system/docker.service.d/http-proxy.conf mode=0666 owner=ubuntu group=docker

- name: Docker as service
  service: name=docker state=restarted

- name: Download Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.6.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0777
    owner: ubuntu
    group: docker
